version: '3'
services:
  dragg:
    build:
      context: ../
      dockerfile: ./training/Dockerfile
    environment:
    - REDIS_HOST=redis
    - localhost=6397
    depends_on:
      - redis
    volumes:
      - ./outputs:/gnomes-rl/submission
  redis:
    image: redis
